version: 2.1

jobs:
  swift-package:
    executor: xcode-14
    steps:
      - setup
      - run: swift build
      - run: swift test

  lint-pod:
    executor: xcode-14
    steps:
      - setup
      - lint-pod

  fastlane-tests:
    executor: xcode-14
    steps:
      - setup
      - run: bundle exec fastlane test_all

  fastlane-tests-xcode-15:
    executor: xcode-15
    steps:
      - setup
      - run: bundle exec fastlane test_all

  deploy-to-cocoapods:
    executor: xcode-14
    steps:
      - setup
      - run: bundle exec pod trunk push

executors:
  xcode-14:
    macos:
      xcode: "14.3.1"
    resource_class: macos.m1.large.gen1
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail
  xcode-15:
    macos:
      xcode: "15.1.0"
    resource_class: macos.m1.large.gen1
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      HOMEBREW_NO_AUTO_UPDATE: 1
    shell: /bin/bash --login -eo pipefail

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - restore-gems

  restore-gems:
    description: "Restore Ruby Gems"
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-3.0.6" > ~/.ruby-version
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle config set --local path 'vendor/bundle' && bundle install
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  lint-pod:
    description: "Lints podspec with specified Swift version"
    parameters:
      swift-version:
        type: string
        default: "5.0"
    steps:
      - run: bundle exec pod lib lint --swift-version=<< parameters.swift-version >>

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - swift-package:
          filters:
            tags:
              only: /.*/
      - fastlane-tests:
          filters:
            tags:
              only: /.*/
      - fastlane-tests-xcode-15:
          filters:
            tags:
              only: /.*/
      - lint-pod:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          context: CocoaPods
          requires:
            - swift-package
            - fastlane-tests
            - fastlane-tests-xcode-15
            - lint-pod
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
